DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "film" CASCADE;
DROP TABLE IF EXISTS "actor" CASCADE;
DROP TABLE IF EXISTS "film_actor" CASCADE;

DROP SEQUENCE IF EXISTS user_id_seq;
DROP SEQUENCE IF EXISTS film_id_seq;
DROP SEQUENCE IF EXISTS actor_id_seq;
DROP SEQUENCE IF EXISTS film_actor_id_seq;